In [2]:
import numpy as np
import pandas as pd

In [9]:
d=pd.read_csv('C:\\Users\\exam2\\Desktop\\winequality-red.csv')
print(d)
wines=np.genfromtxt('C:\\Users\\exam2\\Desktop\\winequality-red.csv',delimiter=';',skip_header=1)
print(wines)

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                

2.	Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float.

In [76]:
wines=np.genfromtxt('C:\\Users\\exam2\\Desktop\\winequality-red.csv',delimiter=';',skip_header=1,dtype=np.float64)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


3.	Identify the shape of the array.

In [15]:
print(wines.shape)

(1599, 12)


4.	Display the element at row 3 and column 4.

In [19]:
print(wines[2][3])

2.3


5.Display the first three items from the fourth column.

In [24]:
print(wines[0:3,3])

[1.9 2.6 2.3]


6.	Display third column from each row


In [26]:
print(wines[:,2])

[0.   0.   0.04 ... 0.13 0.12 0.47]


7.	Display fourth row.

In [28]:
print(wines[3])

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


8.	Assign value 10 to 2nd row and 6th column element.

In [31]:
wines[1][5]=10
print(wines[1,5])

10.0


9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.

In [44]:
slice_new=wines[:,9]
print(slice_new)
slice_new[:]=666
print(slice_new)

[0.56 0.68 0.65 ... 0.75 0.71 0.66]
[666. 666. 666. ... 666. 666. 666.]


10.	Display wines array.

In [36]:
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


11.	Find the data type of wines array and Change the data type to int.

In [61]:
print(wines.dtype)
wines=np.array(wines,dtype='int64')
print(wines)

int64
[[  7   0   0 ... 666   9  85]
 [  7   0   0 ... 666   9  85]
 [  7   0   0 ... 666   9  85]
 ...
 [  6   0   0 ... 666  11  86]
 [  5   0   0 ... 666  10  85]
 [  6   0   0 ... 666  11  86]]


12.	Add 10 points to each quality score.

In [64]:
print(wines[:,-1])
wines[:,-1]=wines[:,-1]+10
print(wines[:,-1])

[5. 5. 5. ... 6. 5. 6.]
[15. 15. 15. ... 16. 15. 16.]


13.	Find the sum of all the elements in an array

In [65]:
print(np.sum(wines))

168074.78194


14.	Find the sum of all the values in every column.

In [66]:
print(np.sum(wines,axis=0))
# s=np.array([[1,2,3],[1,2,3]])
# print(np.sum(s,axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35    25002.     ]


15.	Find the sum of all the values in every row.

In [67]:
print(np.sum(wines,axis=1))

[ 84.5438  133.0548  109.699   ... 110.48174 115.21547 102.49249]


16.	Add the quality column to itself.

In [72]:
wines[:,-1]=wines[:,-1]*2
print(wines[:,-1])

[20. 20. 20. ... 24. 20. 24.]


17.	Multiply alcohol by quality.

In [79]:
print(wines[:,-1]*wines[:,-2])

[47. 49. 49. ... 66. 51. 66.]


18.	Display which wines have a quality rating higher than 5.

In [81]:
print(wines[wines[:,-1]>5])

[[11.2   0.28  0.56 ...  0.58  9.8   6.  ]
 [ 7.3   0.65  0.   ...  0.47 10.    7.  ]
 [ 7.8   0.58  0.02 ...  0.57  9.5   7.  ]
 ...
 [ 5.9   0.55  0.1  ...  0.76 11.2   6.  ]
 [ 6.3   0.51  0.13 ...  0.75 11.    6.  ]
 [ 6.    0.31  0.47 ...  0.66 11.    6.  ]]


19.	Check if any wines have a quality rating equal to 10.

In [86]:
print(wines[wines[:,-1]==10])

[]


20.	Select rows in wines where the quality is over 7

In [88]:
print(wines[wines[:,-1]>7])

[[7.9000e+00 3.5000e-01 4.6000e-01 3.6000e+00 7.8000e-02 1.5000e+01
  3.7000e+01 9.9730e-01 3.3500e+00 8.6000e-01 1.2800e+01 8.0000e+00]
 [1.0300e+01 3.2000e-01 4.5000e-01 6.4000e+00 7.3000e-02 5.0000e+00
  1.3000e+01 9.9760e-01 3.2300e+00 8.2000e-01 1.2600e+01 8.0000e+00]
 [5.6000e+00 8.5000e-01 5.0000e-02 1.4000e+00 4.5000e-02 1.2000e+01
  8.8000e+01 9.9240e-01 3.5600e+00 8.2000e-01 1.2900e+01 8.0000e+00]
 [1.2600e+01 3.1000e-01 7.2000e-01 2.2000e+00 7.2000e-02 6.0000e+00
  2.9000e+01 9.9870e-01 2.8800e+00 8.2000e-01 9.8000e+00 8.0000e+00]
 [1.1300e+01 6.2000e-01 6.7000e-01 5.2000e+00 8.6000e-02 6.0000e+00
  1.9000e+01 9.9880e-01 3.2200e+00 6.9000e-01 1.3400e+01 8.0000e+00]
 [9.4000e+00 3.0000e-01 5.6000e-01 2.8000e+00 8.0000e-02 6.0000e+00
  1.7000e+01 9.9640e-01 3.1500e+00 9.2000e-01 1.1700e+01 8.0000e+00]
 [1.0700e+01 3.5000e-01 5.3000e-01 2.6000e+00 7.0000e-02 5.0000e+00
  1.6000e+01 9.9720e-01 3.1500e+00 6.5000e-01 1.1000e+01 8.0000e+00]
 [1.0700e+01 3.5000e-01 5.3000e-01 2.6000

21.	Display wines with alcohol greater than 10 and quality greater than 7.

In [98]:
s=(wines[:,-1]>7) & (wines[:,-2]>10)
print(wines[s])

[[7.9000e+00 3.5000e-01 4.6000e-01 3.6000e+00 7.8000e-02 1.5000e+01
  3.7000e+01 9.9730e-01 3.3500e+00 8.6000e-01 1.2800e+01 8.0000e+00]
 [1.0300e+01 3.2000e-01 4.5000e-01 6.4000e+00 7.3000e-02 5.0000e+00
  1.3000e+01 9.9760e-01 3.2300e+00 8.2000e-01 1.2600e+01 8.0000e+00]
 [5.6000e+00 8.5000e-01 5.0000e-02 1.4000e+00 4.5000e-02 1.2000e+01
  8.8000e+01 9.9240e-01 3.5600e+00 8.2000e-01 1.2900e+01 8.0000e+00]
 [1.1300e+01 6.2000e-01 6.7000e-01 5.2000e+00 8.6000e-02 6.0000e+00
  1.9000e+01 9.9880e-01 3.2200e+00 6.9000e-01 1.3400e+01 8.0000e+00]
 [9.4000e+00 3.0000e-01 5.6000e-01 2.8000e+00 8.0000e-02 6.0000e+00
  1.7000e+01 9.9640e-01 3.1500e+00 9.2000e-01 1.1700e+01 8.0000e+00]
 [1.0700e+01 3.5000e-01 5.3000e-01 2.6000e+00 7.0000e-02 5.0000e+00
  1.6000e+01 9.9720e-01 3.1500e+00 6.5000e-01 1.1000e+01 8.0000e+00]
 [1.0700e+01 3.5000e-01 5.3000e-01 2.6000e+00 7.0000e-02 5.0000e+00
  1.6000e+01 9.9720e-01 3.1500e+00 6.5000e-01 1.1000e+01 8.0000e+00]
 [5.0000e+00 4.2000e-01 2.4000e-01 2.0000

22.	Change the shape of wines array.

In [109]:
# print(wines.shape)
wines=np.array(wines.reshape((12,1599)))
print(wines.shape)

(12, 1599)
