In [1]:
import numpy as np
import pandas as pd

. Using Numpy, write a basic array of operations on single array to add x to each element of array and subtract y from each element of array. 

In [3]:
s=np.array([1,2,3,4])
print(s+5)
print(s-3)

[6 7 8 9]
[-2 -1  0  1]


. Using Numpy, write a program to add, subtract and multiply two matrices. 

In [5]:
s=np.array([[1,2,3,4],[5,6,7,8]])
p=np.array([[10,11,12,13],[14,15,16,17]])
print(s+p)
print(s-p)
print(s*p)

[[11 13 15 17]
 [19 21 23 25]]
[[-9 -9 -9 -9]
 [-9 -9 -9 -9]]
[[ 10  22  36  52]
 [ 70  90 112 136]]


i)	Create multi-dimensional arrays and find its shape and dimension 

In [10]:
s=np.array([[[1,2,3],[1,2,3]],[[2,3,4],[2,3,4]]])
print(s.shape)
print(s.ndim)

(2, 2, 3)
3


ii)	Create a matrix full of zeros and ones 

In [17]:
k=np.zeros([3,3])
print(k)
l=np.ones([2,4])
print(l)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


iii)	Reshape and flatten data in the array 

In [23]:
s=np.arange(6).reshape(2,3)
print(s)
# a=np.array([2,3,4])
print(s.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


iv)	Append data vertically and horizontally 

In [36]:
s=np.array([0,9,8])
row=np.array([1,2,3])
col=np.array([4,5,6])
print(np.vstack((s,row)))
print(np.hstack((s,col)))

[[0 9 8]
 [1 2 3]]
[0 9 8 4 5 6]


v)	Apply indexing and slicing on array 

In [44]:
s=np.array([[1,2,3],[4,5,6]])
print(s[0][2])
print(s[:,[1,2]])

3
[[2 3]
 [5 6]]


vi)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [54]:
print(s.min())
print(s.max())
print(s.mean())
print(s.std())
print(np.median(s))

1
6
3.5
1.707825127659933
3.5


vii)	Dot and matrix product of two arrays 

In [61]:
print(np.dot(s,s.T))
print(s*s)

[[14 32]
 [32 77]]
[[ 1  4  9]
 [16 25 36]]


viii)	Compute the Eigen values of a matrix 

In [72]:
s=np.array([[1,2],[2,3]])
e,evec=np.linalg.eig(s)
print(e)

[-0.23606798  4.23606798]


ix)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [80]:
D=np.linalg.det([[3,1],[1,2]])
d1=np.linalg.det([[9,8],[1,2]])                                                                                                                                                                                                                              
d2=np.linalg.det([[3,1],[9,8]])
print(f' the value of x0 is \n{d1/D}\n and the value of x1 is\n {d2/D}')

 the value of x0 is 
2.0
 and the value of x1 is
 2.9999999999999996


x)	Compute the multiplicative inverse of a matrix 

In [81]:
print(np.linalg.inv(s))

[[-3.  2.]
 [ 2. -1.]]


xi)	Compute the rank of a matrix 

In [83]:
print(np.linalg.matrix_rank(s))

2


Compute the determinant of an array

In [84]:
print(np.linalg.det(s))

-1.0
